# Exclude everything
**
# Re-include only what the Dockerfile COPYs
!popcorn/
!popcorn/elixir/
!popcorn/elixir/**

!local-live-view/
!local-live-view/**

!examples/
!examples/local-lv-burrito/
!examples/local-lv-burrito/**
