[tools]
elixir = "1.17.3-otp-26"
erlang = "26.0.2"
node = "22"
pnpm = "latest"
rebar = "latest"
watchexec = "latest"

[tasks.dev]
run = "scripts/dev.sh"
description = "Start dev mode"

[tasks.test]
run = "scripts/test.sh"
description = "Run tests"

[tasks.build-vm]
run = "scripts/build-atomvm.sh"
description = "Build AtomVM"

[tasks.build-openssl]
run = "scripts/build-openssl.sh"
description = "Build OpenSSL for WASM"

[tasks.build-otp]
run = "scripts/build-beam.sh"
description = "Build OTP/BEAM for WASM"

[tasks.build-otp-js]
depends = ["build-otp debug"]
run = "pnpm -F ./otp/js build"
description = "Build JS part of OTP/BEAM interop"

[tasks.build-otp-with-crypto]
run = "scripts/build-beam.sh --with-crypto"
description = "Build OTP/BEAM for WASM with crypto/asn1 NIFs"

[tasks.regenerate-otp-patches]
run = "scripts/patch-beam.sh --regen"
description = "Regenerate OTP patches from current otp/sources/otp state"

[tasks.clean]
run = "scripts/clean.sh"
description = "Clean build artifacts"
