packages:
  - "otp/js"
  - "otp/js/e2e/setup"
  - "popcorn/js"
  - "popcorn/js/e2e/setup"
  - "popcorn/elixir/test/fixtures/wasm/assets"
  - "examples/hello-react"
  - "examples/hello-popcorn/assets"
  - "examples/eval-in-wasm/assets"
  - "examples/iex-wasm/assets"
  - "examples/game-of-life/assets"
  - "examples/local-lv-compare/assets"
  - "examples/local-lv-forms/assets"
  - "examples/local-lv-thermostat/assets"
  - "local-live-view/assets"
  - "landing-page"
  - "language-tour"

catalog:
  "@types/node": ^25.0.8
  vite: ^7.3.1
  typescript: ^5.9.3
  eslint: ^9.39.2
