defmodule LocalThermostatWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :local_thermostat
  plug :put_wasm_security_headers

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_local_thermostat_key",
    signing_salt: "yh35HOaz",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  socket "/llv_socket", LocalLiveView.Socket, websocket: true

  plug Plug.Static,
    at: "/",
    from: :local_thermostat,
    gzip: not code_reloading?,
    only: LocalThermostatWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug LocalThermostatWeb.Router

  defp put_wasm_security_headers(conn, _opts) do
    conn
    |> Plug.Conn.put_resp_header("cross-origin-opener-policy", "same-origin")
    |> Plug.Conn.put_resp_header("cross-origin-embedder-policy", "require-corp")
  end
end
