# Exclude everything
**
# Re-include only what the Dockerfile COPYs
!popcorn/
!popcorn-2/elixir/
!popcorn-2/elixir/**

!local-live-view/
!local-live-view/**

!examples/
!examples/local-lv-burrito/
!examples/local-lv-burrito/**
