defmodule LocalLiveView.SSR do
  @moduledoc """
  Renders a `LocalLiveView` on the server.

  `LocalLiveView.Component.local_live_view/1` uses it to fill the view's mount
  point with HTML on the initial page load, so the view is visible before the
  Wasm runtime boots. Once the runtime mounts the view in the browser, its
  first render is patched onto that HTML, the same way Phoenix LiveView patches
  its connected render onto the dead one.

  The view goes through the same lifecycle as in the browser: `c:LocalLiveView.mount/3`,
  `c:LocalLiveView.update/2` with the assigns from the component, and
  `c:LocalLiveView.handle_params/3`, then `c:LocalLiveView.render/1`. The socket
  is not `LocalLiveView.connected?/1` at that point, so the view can skip
  browser-only work.

  The view module has to be compiled on the host for this to work — the `local/`
  project generated by `mix llv.install` compiles its `lib/` for every target.
  """

  alias LocalLiveView.Lifecycle
  alias Phoenix.LiveView.{Diff, Rendered, Socket}

  @typedoc "Why the view was not rendered."
  @type skip_reason :: :not_loaded | :redirected

  @doc """
  Renders `view` (a module name, as given to `<.local_live_view view="..." />`)
  with the assigns the component received.

  Returns `{:ok, html}` with the rendered iodata, or `{:error, reason}` when:

    * `:not_loaded` - the view module is not available on the host,
    * `:redirected` - the view redirected during mount; the browser mount will
      perform the redirect.

  Errors raised by the view's callbacks propagate.

  ## Options

    * `:id` - the DOM id of the view, the same the component renders
    * `:url` - the URL of the page, passed to `c:LocalLiveView.handle_params/3`.
      Without it `handle_params/3` gets no params and a `nil` URL.
    * `:endpoint` - the endpoint to put in the socket; defaults to
      `:default_endpoint` from the `:local_live_view` application env
    * `:mirror_id` - the id of the view's mirror channel, if any
  """
  @spec render(String.t(), map(), keyword()) :: {:ok, iodata()} | {:error, skip_reason()}
  def render(view, assigns, opts \\ []) when is_binary(view) and is_map(assigns) do
    module = Module.concat([view])

    with {:module, ^module} <- Code.ensure_loaded(module),
         true <- function_exported?(module, :render, 1) do
      do_render(module, assigns, opts)
    else
      _ -> {:error, :not_loaded}
    end
  end

  defp do_render(module, assigns, opts) do
    url = opts[:url]
    socket = build_socket(module, opts)

    {socket, _mount_opts} = Lifecycle.mount(module, :not_mounted_at_router, %{}, socket)

    socket =
      socket
      |> then(&Lifecycle.update!(module, assigns, &1))
      |> then(&Lifecycle.handle_params(module, url, &1))

    if socket.redirected do
      {:error, :redirected}
    else
      rendered = to_rendered(socket, module)

      {diff, _prints, _components} =
        Diff.render(socket, rendered, Diff.new_fingerprints(), Diff.new_components())

      {:ok, Diff.to_iodata(diff)}
    end
  end

  # What Phoenix.LiveView.Renderer.to_rendered/2 does for a LiveView, minus
  # the layout: a LocalLiveView has none.
  defp to_rendered(socket, module) do
    assigns = socket.assigns
    socket = %{socket | assigns: %Socket.AssignsNotInSocket{__assigns__: assigns}}

    case module.render(Map.put(assigns, :socket, socket)) do
      %Rendered{} = rendered ->
        rendered

      other ->
        raise ArgumentError, """
        expected #{inspect(module)}.render/1 to return a %Phoenix.LiveView.Rendered{}, got:

        #{inspect(other)}
        """
    end
  end

  # Mirrors the socket the view gets in the browser (see LocalLiveView.Proxy),
  # minus the transport: no transport_pid makes connected?/1 false.
  defp build_socket(module, opts) do
    %Socket{
      id: opts[:id],
      endpoint: opts[:endpoint] || Application.get_env(:local_live_view, :default_endpoint),
      view: module,
      host_uri: host_uri(opts[:url]),
      assigns: %{__changed__: %{}, flash: %{}, live_action: nil},
      private: %{
        live_temp: %{},
        conn_session: %{},
        root_view: module,
        llv_view: module,
        llv_id: opts[:id],
        mirror_id: opts[:mirror_id]
      }
    }
  end

  defp host_uri(nil), do: :not_mounted_at_router

  defp host_uri(url) do
    case URI.parse(url) do
      %URI{host: host} = uri when is_binary(host) ->
        %URI{scheme: uri.scheme, host: host, port: uri.port}

      _relative ->
        :not_mounted_at_router
    end
  end
end
