defmodule Mix.Tasks.Popcorn.SimpleServer do
  @moduledoc """
  Generates a simple static file server script to host
  assets generated by Popcorn.
  """
  @shortdoc @moduledoc

  use Mix.Task

  @priv_dir :code.priv_dir(:popcorn)

  @impl true
  def run(_args) do
    File.cp!(Path.join(@priv_dir, "server.exs"), "server.exs")
  end
end
