defmodule Mix.Tasks.Popcorn.SimpleServer do
  @shortdoc """
  Generates a simple static file server script to host
  assets generated by Popcorn.
  """
  @moduledoc """
  #{@shortdoc}

  These assets can also be hosted with any other server,
  but it has to add the following HTTP headers:

  ```txt
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Embedder-Policy: require-corp
  ```

  Otherwise the browser refuses to run WASM.
  """
  @shortdoc @moduledoc

  use Mix.Task

  @priv_dir :code.priv_dir(:popcorn)

  @impl true
  def run(_args) do
    File.cp!(Path.join(@priv_dir, "server.exs"), "server.exs")
  end
end
