name: Setup Toolchain
description: Install emsdk, Elixir/OTP, and AtomVM system dependencies

runs:
  using: composite
  steps:
    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 4.0.8

    - name: Set up Elixir
      uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1.24.0
      with:
        elixir-version: "1.17.3"
        otp-version: "26.0.2"
        rebar3-version: "3.18.0"

    - name: Install AtomVM deps
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y gperf libmbedtls-dev zlib1g-dev
