# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Eval in WASM Build & test

on:
  push:
    branches: ["**"]
    paths:
      - "examples/eval-in-wasm/**"
      - ".github/workflows/eval_in_wasm_build_test.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CI: true
  MIX_ENV: test

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: examples/eval-in-wasm

    steps:
      - uses: actions/checkout@v4

      - name: Setup toolchain
        uses: ./.github/actions/setup-toolchain

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: examples/eval-in-wasm/deps
          key: ${{ runner.os }}-mix-eval_in_wasm-${{ hashFiles('examples/eval-in-wasm/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-eval_in_wasm-

      - name: Install Hex dependencies
        run: mix deps.get

      - name: Build AtomVM
        uses: ./.github/actions/build-atomvm
        with:
          working-directory: examples/eval-in-wasm
          build-mode: debug-wasm
          outdir: popcorn_runtime_source/artifacts/wasm
          cmake-opts: "SANITIZER=OFF"

      - name: Compile Hex dependencies
        run: mix deps.compile

      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright
        with:
          cache-prefix: examples-eval-in-wasm
          lockfile: examples/eval-in-wasm/mix.lock

      - name: Configure runtime source
        run: |
          echo "config :popcorn, runtime: {:path, \"popcorn_runtime_source/artifacts/\$target\"}" >> config/config.exs

      - name: Cook
        run: mix popcorn.cook --js

      - name: Run tests
        run: mix test --no-start
