# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Eval in WASM Build & test

on:
  push:
    branches: ["**"]
    paths:
      - "examples/eval_in_wasm/**"
      - ".github/workflows/eval_in_wasm_build_test.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CI: true
  MIX_ENV: test

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: examples/eval_in_wasm

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-toolchain

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: examples/eval_in_wasm/deps
          key: ${{ runner.os }}-mix-eval_in_wasm-${{ hashFiles('examples/eval_in_wasm/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-eval_in_wasm-

      - name: Install dependencies
        run: mix deps.get

      - uses: ./.github/actions/build-atomvm
        with:
          working-directory: examples/eval_in_wasm
          build-mode: debug-wasm
          outdir: popcorn_runtime_source/artifacts/wasm
          cmake-opts: "SANITIZER=OFF"

      - name: Compile dependencies
        run: mix deps.compile

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-examples-eval-in-wasm-${{ hashFiles('examples/eval_in_wasm/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-playwright-examples-eval-in-wasm-
            ${{ runner.os }}-playwright-

      - name: Install Playwright deps
        run: mix playwright.install

      - name: Configure runtime source
        run: |
          echo "config :popcorn, runtime: {:path, \"popcorn_runtime_source/artifacts/\$target\"}" >> config/config.exs

      - name: Cook
        run: mix popcorn.cook

      - name: Run tests
        run: mix test --no-start
