# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Hello Popcorn - Build & test

on:
  push:
    branches: ["**"]
    paths:
      - "**"
      - "!misc/**"
      - "!examples/**"
      - "examples/hello_popcorn/**"
      - "!.github/**"
      - ".github/workflows/hello_popcorn_build_test.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CI: true
  MIX_ENV: test

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: examples/hello_popcorn

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-toolchain

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: examples/hello_popcorn/deps
          key: ${{ runner.os }}-mix-hello_popcorn-${{ hashFiles('examples/hello_popcorn/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-hello_popcorn-

      - name: Install dependencies
        run: mix deps.get

      - uses: ./.github/actions/build-atomvm
        with:
          working-directory: examples/hello_popcorn
          build-mode: debug-wasm
          outdir: popcorn_runtime_source/artifacts/wasm
          cmake-opts: "SANITIZER=OFF"

      - name: Compile dependencies
        run: mix deps.compile

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-examples-hello-popcorn-${{ hashFiles('examples/hello_popcorn/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-playwright-examples-hello-popcorn-
            ${{ runner.os }}-playwright-

      - name: Install Playwright deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install chromium

      - name: Configure runtime source
        run: |
          echo "config :popcorn, runtime: {:path, \"popcorn_runtime_source/artifacts/\$target\"}" >> config/config.exs

      - name: Cook
        run: mix popcorn.cook

      - name: Run tests
        run: mix test --no-start
