# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: LocalLiveView - Build

on:
  push:
    branches: ["**"]
    paths:
      - "examples/local_live_view/**"
      - "examples/local_thermostat/**"
      - "examples/compare_live_views/**"
      - "examples/local_form_demo/**"
      - ".github/workflows/local_live_view_build.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CI: true
  MIX_ENV: test

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: examples/local_live_view

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-toolchain

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: examples/local_live_view/deps
          key: ${{ runner.os }}-mix-local_live_view-${{ hashFiles('examples/local_live_view/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-local_live_view-

      - name: Install dependencies
        run: mix deps.get

      - uses: ./.github/actions/build-atomvm
        with:
          working-directory: examples/local_live_view
          build-mode: debug-wasm
          outdir: popcorn_runtime_source/artifacts/wasm
          cmake-opts: "SANITIZER=OFF"

      - name: Compile dependencies
        run: mix deps.compile

      - name: Lint
        run: mix lint

      - name: Configure runtime source
        run: |
          echo "config :popcorn, runtime: {:path, \"popcorn_runtime_source/artifacts/\$target\"}" >> config/config.exs

      - name: Cook
        run: mix popcorn.cook
