# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Popcorn build & test

on:
  push:
    branches: ["**"]
    paths:
      - "**"
      - "!examples/**"
      - "!misc/**"
      - "!.github/**"
      - ".github/workflows/popcorn_build_test.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CI: true
  MIX_ENV: test

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup toolchain
        uses: ./.github/actions/setup-toolchain

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-root-${{ hashFiles('mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-root-

      - name: Install dependencies
        run: mix deps.get

      - name: Build AtomVM Unix
        uses: ./.github/actions/build-atomvm
        with:
          build-mode: debug-unix
          outdir: atomvm-build/unix
          cmake-opts: "SANITIZER=OFF DEBUG_ASSERTIONS=ON DEBUG_GC=ON"

      - name: Build AtomVM WASM
        uses: ./.github/actions/build-atomvm
        with:
          build-mode: debug-wasm
          outdir: atomvm-build/wasm

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-popcorn-root-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-playwright-popcorn-root-
            ${{ runner.os }}-playwright-

      - name: Install Playwright deps
        run: mix playwright.install

      - name: Lint
        run: mix lint

      - name: Configure runtime source
        run: |
          echo "config :popcorn, runtime: {:path, \"atomvm-build/\$target\"}" >> config/config.exs

      - name: Run tests
        run: mix test

      - name: Run WASM tests
        run: TARGET=wasm mix test
