# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Popcorn tree-shake test

on:
  push:
    branches: ["**"]
    paths:
      - "popcorn/elixir/lib/treeshake/**"
      - "popcorn/elixir/test/treeshake/**"
      - "popcorn/elixir/test/fixtures/treeshake/**"
      - ".github/**"
      - ".github/workflows/popcorn_treeshake_test.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CI: true
  MIX_ENV: test

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    defaults:
      run:
        working-directory: popcorn/elixir

    steps:
      - uses: actions/checkout@v4

      - name: Setup BEAM
        uses: ./.github/actions/setup-beam

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Node 24.16.0 broke the zip extraction (and subsequently, Playwright).
          # See https://github.com/nodejs/node/issues/63487.
          node-version: "24.15.0"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Restore Mix cache
        uses: actions/cache@v4
        with:
          path: |
            popcorn/elixir/deps
            popcorn/elixir/_build
          key: ${{ runner.os }}-mix-popcorn-elixir-1.17.3-otp-26.0.2-${{ env.MIX_ENV }}-${{ hashFiles('popcorn/elixir/mix.exs', 'popcorn/elixir/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-popcorn-elixir-1.17.3-otp-26.0.2-${{ env.MIX_ENV }}-

      - name: Install Hex dependencies
        run: mix deps.get

      - name: Install JS dependencies
        working-directory: .
        run: pnpm install

      - name: Build AtomVM Unix test runtime
        uses: ./.github/actions/build-atomvm
        with:
          build-mode: debug-unix
          output-directories: popcorn/elixir/test/fixtures/unix
          cmake-opts: "SANITIZER=OFF DEBUG_ASSERTIONS=ON DEBUG_GC=ON"

      - name: Run tests
        # Limiting to test/treeshake avoids compiling other tests
        run: mix test test/treeshake --only treeshake
